services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    container_name: laravel_app
    command: php artisan serve --host=0.0.0.0 --port=8000